aider: Remove ContentMD5 argument from upload_file() function call.
# Aider chat conversation:

USER: I ran this command:

 python test.py

And got this output:

100+0 records in
100+0 records out
104857600 bytes transferred in 0.013150 secs (7973961977 bytes/sec)
md (binary):                    b'/(+\x84\xe7\xe6\x08\xd5\x85$I\xed\x94\x0b\xfcQ'
contents_md5 (base64):          LygrhOfmCNWFJEntlAv8UQ==
The MD5 Hash of this file is:   2f282b84e7e608d5852449ed940bfc51
The file size is: 104857600 bytes
Traceback (most recent call last):
  File "/Users/djh/work/src/github.com/djh00t/module_klingon_file_manager/test.py", line 209, in <module>
    test_large_upload_progress()
  File "/Users/djh/work/src/github.com/djh00t/module_klingon_file_manager/test.py", line 196, in test_large_upload_progress
    s3.upload_file(
TypeError: upload_file() got an unexpected keyword argument 'ContentMD5'

ASSISTANT: The error message is indicating that the `upload_file()` function of the `boto3` library's `s3` client does not accept a `ContentMD5` argument. This function is used to upload a file to an Amazon S3 bucket.

The `upload_file()` function expects the following arguments:

- `Filename`: The name of the file to upload.
- `Bucket`: The name of the S3 bucket to upload to.
- `Key`: The name of the key to use for the uploaded file.

The `ContentMD5` argument is used with the `put_object()` function, not `upload_file()`.

To fix this issue, we need to remove the `ContentMD5` argument from the `upload_file()` function call.

Here is the *SEARCH/REPLACE block* for the required change:

```python
test.py
<<<<<<< SEARCH
    s3.upload_file(
        Filename='./large_file',
        Bucket='fsg-gobbler',
        Key='tests/large_file',
        Callback=progress,
        ContentMD5=contents_md5,
        Metadata=metadata
    )
=======
    s3.upload_file(
        Filename='./large_file',
        Bucket='fsg-gobbler',
        Key='tests/large_file',
        Callback=progress,
        Metadata=metadata
    )
>>>>>>> REPLACE
```

This change will ensure that the `upload_file()` function is called with the correct arguments.